# URL Configuration
urls:
  main_url: "https://knowledge.exlibrisgroup.com/Content/New_and_Upcoming_Collections/Alma_CKB_Release_Notes"
  link_selectors:
    container: "section.mt-content-container"  # Container section that holds the list
    list: "ul li:first-child a"  # Select first link in the list

# Directory Settings
directories:
  logs: "logs"
  data: "data"
  output_dir: "C:/Users/masedet/Tel-Aviv University/masedet - Documents/Data/CKB"  # Base name - timestamp will be appended

# Logging Configuration
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(levelname)s - %(message)s"

# HTML Selectors
selectors:
  section: "rnsub"
  table: "cb-tableizer"
  date_span: "AlmaRNTag"
  title: "h2"

# Date Parsing
date_parsing:
  year: "2024"
  months:
    January: "01"
    February: "02"
    March: "03"
    April: "04"
    May: "05"
    June: "06"
    July: "07"
    August: "08"
    September: "09"
    October: "10"
    November: "11"
    December: "12"

# Table Processing
table_processing:
  metadata_columns:
    - "retrieval_date"
    - "week_number"
    - "update_date"
    - "table_title"

# Deduplication Configuration
deduplication:
  # Key columns used to identify unique rows for each table type
  key_columns:
    "E-collections to Be Removed":
      - "Interface Name"
      - "E-Collection Name"
      - "E-Collection ID"
    
    "New E-collections and Services":
      - "Interface Name"
      - "E-Collection Name"
      - "E-Collection ID"
      
    # Default key columns for any table type not specifically listed
    default:
      - "Interface Name"
      - "E-Collection Name"
      - "E-Collection ID"